# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.TextField(blank=True, max_length=100)),
                ('previous_company', models.TextField(blank=True, max_length=100)),
                ('highest_qualification', models.TextField(blank=True, max_length=100)),
                ('institute_hq', models.TextField(blank=True, max_length=100)),
                ('highschool', models.TextField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sql', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('r', models.BooleanField(default=False)),
                ('scala', models.BooleanField(default=False)),
                ('julia', models.BooleanField(default=False)),
                ('tableau', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
