# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createprofile', '0004_document_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documenta',
        ),
    ]
