# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:35
from __future__ import unicode_literals

import createprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createprofile', '0007_auto_20170309_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[createprofile.validators.validate_cv_extension]),
        ),
    ]
