# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createprofile', '0009_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='photo',
            field=models.ImageField(upload_to='documents/photos/'),
        ),
    ]
