# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:33
from __future__ import unicode_literals

import createprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createprofile', '0011_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='document',
            field=models.FileField(upload_to='documents/jobs/', validators=[createprofile.validators.validate_cv_extension]),
        ),
    ]
