# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createprofile', '0015_auto_20170317_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
