# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=1000)),
                ('email_body', models.TextField(max_length=2000)),
                ('phone_number', models.TextField(blank=True, max_length=200)),
                ('current_occupation', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
